name: Sync changes to Superblocks
on: [push]

jobs:
  superblocks-sync:
    runs-on: ubuntu-latest
    name: Sync to Superblocks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push
        uses: superblocksteam/import-action@v1
        id: push
        with:
          token: 9LArXYAqZ70fgN5WiBuYAW555IFm9nmsH/R5fxKhvTVUjEqK

      - name: Pull
        uses: superblocksteam/export-action@v1
        id: pull
        with:
          token: 9LArXYAqZ70fgN5WiBuYAW555IFm9nmsH/R5fxKhvTVUjEqK
